In [1]:
library(sn)
library(tidyverse)

Loading required package: stats4
Package 'sn', 2.1.1 (2023-04-04). 
Type 'help(SN)' and 'help("overview-sn")' for basic information.
The package redefines function 'sd' but its usual working is unchanged.

Attaching package: ‘sn’

The following object is masked from ‘package:stats’:

    sd

── Attaching core tidyverse packages ────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ──────────────────────────────── tidyverse_conflicts() ──
✖ lubridate::dst() masks sn::dst()
✖ dplyr::filter()  masks stats::filter()
✖ dplyr::lag()     masks stats::lag()
ℹ Use the ]8;;http://conflicted.r-lib.org/conflicted package]8;; to force all conflicts to become errors


In [7]:
Sigma <- matrix(c(1, 0.4, 0.4, 0.6), 2, 2)
cpM <- list(mean=c(0,-1), var.cov=Sigma, gamma1=c(0, -0.6))
dpM <- cp2dp(cpM, family="SN")
yM <- rmsn(10, dp=dpM)



In [8]:
yM

             [,1]        [,2]
 [1,]  0.89722500 -0.57510143
 [2,] -0.98958484 -2.87599104
 [3,]  0.73436469 -0.17740820
 [4,]  0.72581011 -0.53205519
 [5,]  0.73411432 -0.35536255
 [6,] -0.67856632 -2.70707039
 [7,]  0.03145024 -0.69464442
 [8,] -0.37421484 -1.66173224
 [9,]  0.98946194 -0.09636419
[10,]  0.41666741 -1.21762132
attr(,"family")
[1] "SN"
attr(,"parameters")
attr(,"parameters")$xi
[1]  0.000000 -0.133893

attr(,"parameters")$Omega
     [,1]     [,2]
[1,]  1.0 0.400000
[2,]  0.4 1.350141

attr(,"parameters")$alpha
[1]   3.660546 -10.633482

attr(,"parameters")$tau
[1] 0

attr(,"parameters")attr(,"delta.star")
[1] 0.9950209

In [10]:
Omega <- matrix(c(0.15, -0.058, -0.058, 0.093), 2, 2)
dpM <- list(xi=c(0.06, 0.597), Omega=Omega, alpha=c(0.868, -0.561))
yM <- rmsn(1000, dp=dpM)
yM

                 [,1]         [,2]
   [1,]  0.4794056738  0.349874572
   [2,]  0.0749644183  0.335402411
   [3,]  0.1465111630  0.661418315
   [4,]  0.2102531166  0.753514189
   [5,]  0.2431786913 -0.028399895
   [6,]  0.7146601774  0.413584987
   [7,]  0.2995970749  0.719330640
   [8,]  0.2954954042  0.270832664
   [9,]  0.3564881373 -0.052999276
  [10,]  0.1608491223  0.477353508
  [11,]  0.0134963427  0.592840709
  [12,]  0.4618400957  0.494690976
  [13,]  0.3523403578  0.769282973
  [14,]  0.4157901352  0.604064291
  [15,] -0.1980317812  0.705421250
  [16,]  0.5122769720  0.360424499
  [17,]  0.1548261452  0.534343117
  [18,]  0.4202465266  0.200966622
  [19,]  0.2229919835  0.210509795
  [20,]  0.5099742560  0.267808714
  [21,]  0.4864824102  0.535166256
  [22,]  0.7897890119  0.060224847
  [23,]  0.5039801747  0.196858664
  [24,]  0.4108780217  0.609616329
  [25,]  0.3670180923  0.860790346
  [26,]  0.5403901118  0.027763543
  [27,]  0.5333339229  0.523557799
  [28,]  0.595229771